const ActionTypes = {
    BEGIN_LOADING: 'BEGIN_LOADING',
    SHOW_MESSAGE: 'SHOW_MESSAGE',
    HIDE_MESSAGE: 'HIDE_MESSAGE',
    END_LOADING: 'END_LOADING',
    INIT_HOME: 'INIT_HOME',
    SIGNIN: 'SIGNIN',
    REDIRECT: 'REDIRECT',
    CLEAR_PATH: 'CLEAR_PATH'
}
export default ActionTypes;