const ActionTypes = {
    BEGIN_LOADING: 'BEGIN_LOADING',
    SHOW_MESSAGE: 'SHOW_MESSAGE',
    HIDE_MESSAGE: 'HIDE_MESSAGE',
    END_LOADING: 'END_LOADING',
    SIGNIN: 'SIGNIN',
    REDIRECT: 'REDIRECT',
    CLEAR_PATH: 'CLEAR_PATH',
    SHOW_SIGNINERRORMESSAGE: 'SHOW_SIGNINERRORMESSAGE',
    INIT_HOMEPAGE: 'INIT_HOMEPAGE',
    LOAD_HOMEPAGE: 'LOAD_HOMEPAGE'
}
export default ActionTypes;